package lk.dialog.crm;

import lk.dialog.crm.Product;


rule "Offer for Diamond"
	when 
		productObject: Product(type=="Diamond")
	
	then
		productObject.setDiscount(10);
		System.out.println("Product discount >>>>>>>>>>>>"+productObject.getDiscount());
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="Gold")
	then
		productObject.setDiscount(20);
		System.out.println("Product discount >>>>>>>>>>"+productObject.getDiscount());
	end