package lk.dialog.crm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

   static final long serialVersionUID = 1L;

    public Product() {
    }

     String type;
     int discount;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getDiscount() {
        return discount;
    }

    public void setDiscount(int discount) {
        this.discount = discount;
    }




}